branch-defaults:
  main:
    environment: Udagramwebapi-env
deploy:
  artifact: ./Archive.zip
environment-defaults:
  Udagramapi-env:
    branch: null
    repository: null
global:
  application_name: udagram-web-api
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
